version: '3'
services:
  store:
    image: store
    build: 
      context: ./store
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/store
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      - postgres
    networks:
      common_network:
        ipv4_address: 172.20.0.22

  postgres:
    image: postgres:alpine
    environment:
      - POSTGRES_DB=store
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    ports:
      - '5432:5432'
    networks:
      common_network:
        ipv4_address: 172.20.0.23

networks:
  common_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16

    
