openapi: 3.0.0
info:
  title: Backend приложения для корпоративной геймификации
  version: 1.0.0
paths:
  /api/v01/store/items:
    get:
      summary: Получить полный список предметов магазина
      tags: 
        - 'Магазин'
      responses:
        '200':
          description: Список всех предметов мазагина
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/item"

components:
  schemas:
    item:
      type: object
      properties:
        item_id:
          type: integer
          example: 1
        name:
          type: string
          example: "Шампунь джумай сынба"
        description:
          type: string
          example: null
        price:
          type: number
          example: 102.2
        category:
          type: string
          example: средства гигиены
