spring:
    application:
        name: store
    datasource:
        url: jdbc:postgresql://localhost:5432/store
        username: root
        password: root
    jpa:
        hibernate:
            ddl-auto: create
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect

logging:
    level:
        org:
            springframework:
                security: debug

gigachat:
    authtoken: ${GIGACHAT_AUTHTOKEN}

qrcode:
    url:
        host: ${QRCODE_URL_HOST:localhost}
        port: ${QRCODE_URL_PORT:5173}
        